apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
  labels:
    storage.k8s.io/name: glusterfs
subsets:
  - addresses:
      - ip: 192.168.100.1
        hostname: k8s1
      - ip: 192.168.100.2
        hostname: k8s2
    ports:
      - port: 1
