apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluster-claim  
spec:
  # storageClassName: manual
  accessModes:
  - ReadWriteMany      
  resources:
     requests:
       storage: 256Mi
