apiVersion: v1
kind: Pod
metadata:
  name: test-pod

spec:
  volumes:
  - name: gluster-vol
    persistentVolumeClaim:
      claimName: gluster-claim

  containers:
    - name: gluster-pvc-test
      image: nginx:alpine
      ports:
      - containerPort: 80

      volumeMounts:
        - name: gluster-vol
          mountPath: /vol
