apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: k8s-test-ca
  duration: 87696h # 10y
  renewBefore: 360h # 15d
  subject:
    organizations:
      - test
    organizationalUnits:
      - k8s
  secretName: test-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
